CREATE DOMAIN DM_ID AS INTEGER NOT NULL;
CREATE DOMAIN DM_NAME AS VARCHAR(100);
CREATE DOMAIN DM_DATE AS DATE;
CREATE TABLE USERS (ID DM_ID, NAME DM_NAME, CREATED_AT DM_DATE);
CREATE TABLE ORDERS (ID DM_ID, USER_ID DM_ID, ORDER_DATE DM_DATE);

CREATE PROCEDURE ADD_NUMBERS (A INT, B INT)
RETURNS (C INT)
AS
BEGIN
    C = A + B;
END;

CREATE PROCEDURE TEST_PROC
RETURNS (X INT)
AS
BEGIN
    X = 123;
END;
